### ISSUE TITLE
Bug with giveaway

### ISSUE THREAD

**Issue by sadoj-kuro** [PumPum7/PumCogs#1]
**Describe the bug**
Error on loading cog

**To Reproduce**
loading cog giveaway

**Expected behavior**
https://hastebin.com/ruxoqiyuri.sql

**Discord Version**
 - Stable lasted version

**Python Version**
3.6

**Comment by PumPum7** [comment]
Are you sure that you use the newest version of the bot?

**Comment by sadoj-kuro** [comment]
yes v3

**Comment by PumPum7** [comment]
Can you make sure that there are no updates available for your Red V3?

**Comment by sadoj-kuro** [comment]
i'm sure i have look no update available

**Comment by PumPum7** [comment]
What is your red version? (exact number please)

**Comment by sadoj-kuro** [comment]
3.0.0rc1

**Comment by sadoj-kuro** [comment]
3.0.0rc1

**Comment by PumPum7** [comment]
This error should be fixed now

**Comment by sadoj-kuro** [comment]
same prob ... no module redbot
