### ISSUE TITLE
Nicknamechanger (same error as lastime)

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [PumPum7/PumCogs#11]
**Describe the bug**
Same problem again with nicknamechanger as last time with hastebin now giving 

    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'

**To Reproduce**
Use the check command

**Expected behavior**
Checks names and gives a link to the changed names. 

**Screenshots**

**Discord Version**
Canary
Latest

**Python Version**
Python 3.7

**Additional context**

**Comment by Ianardo-DiCaprio** [comment]
Update: seems to be working again. Guessing hastebin changed something and then changed it back.

**Comment by PumPum7** [comment]
Its an API error, when the API is down it can happen.
