### ISSUE TITLE
Lookup error

### ISSUE THREAD

**Issue by xNightWulf** [PumPum7/PumCogs#2]
**Describe the bug**

**To Reproduce**
1. Create a giveaway 
2. See error

**Expected behavior**

A giveaway to be made and a winner to be announced.

**Screenshots**
https://i.imgur.com/VQxMFYo.png

**Discord Version**
 - Canary
 - Latest version

**Python Version**
I'm using python 3.6

**Additional context**
When creating a giveaway it says "Something didn't go quite right: Command raised an exception: LookupError: No trigger by the name "date" was found. Please report this." however it still creates the giveaway. But when the time is up it doesn't announce a winner.

**Comment by PumPum7** [comment]
Open cmd and type `pip install apscheduler` it should be fixed then
