### ISSUE TITLE
Imageediting

### ISSUE THREAD

**Issue by xNightWulf** [PumPum7/PumCogs#3]
**Describe the bug**
Failing to load cog

**To Reproduce**
1. Trying to load cog
2. See error

**Expected behavior**

The cog to be loaded

**Discord Version**
Canary
latest update

**Python Version**
Python 3.6

**Additional context**
I get "Failed to load package imageediting. Check your console or logs for details."
And then in the console I get "ImportError: cannot import name 'imageediting'"

**Comment by PumPum7** [comment]
What is your Red version?
