### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [PumPum7/PumCogs#4]
**Describe the bug**
giveaway and imageediting no longer works after updating red.
**To Reproduce**
1. update red
2. Try to load cogs

**Expected behavior**
Giveaway and imageediting to be loaded
**Screenshots**

**Discord Version**
Canary
Yes

**Python Version**
3.6

**Additional context**
The error code is: 

RuntimeError: The Giveaway cog in the giveaway.giveaway package does not inherit from the commands.Cog base class. 
The cog author must update the cog to adhere to this requirement.

**Comment by PumPum7** [comment]
it doesn't support the newest version of Red yet
