### ISSUE TITLE
Nicknamechanger Request

### ISSUE THREAD

**Issue by Ianardo-DiCaprio** [PumPum7/PumCogs#9]
I use this frequently to change nicknames of users that are not standard characters in a few servers of mine. Having to use the command all the time is quite annoying though. My request is that it checks the name when the users joins the server so that it automatically changes the name to use standard characters.

**Comment by PumPum7** [comment]
Not a thing I will add in the Red version. If someone wants to rewrite my version which I use with my private bot so it works with the Red DBs then I can send them the file and they can just make a pull request.

**Comment by Ianardo-DiCaprio** [comment]
Instead of making it automatic, could you add an option that listens for a trigger word, instead of clicking the reaction, so that I could set up schedules to run that run the [p]check command and shortly after say the trigger word so it runs the command on a schedule

**Comment by PumPum7** [comment]
I mean if you only want it for one server then I can edit the file and send it to you so it automatically changes it. For an open bot it's better to make it optional.

**Comment by Ianardo-DiCaprio** [comment]
Well, if it also listened for a word, as well as a react, it could be used normally, or could be used with a mock say with scheduler so that it can be automatic in whatever servers you want it in.

**Comment by PumPum7** [comment]
Like already said I can give you a version of it which automatically edits it but I will not add it to the public release, as I am not going to make it a feature you have to use

**Comment by Ianardo-DiCaprio** [comment]
I went ahead and changed it myself to accept a reaction or a yes/y message to run so that I can now run it with the scheduler cog to do it automatically.
